//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGG.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailabilitySet
    {
        public int Id { get; set; }
        public int IdFirm { get; set; }
        public int IdCar { get; set; }
    
        public virtual CarsSet CarsSet { get; set; }
        public virtual FirmsSet FirmsSet { get; set; }
    }
}
