//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGG.com
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmsSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirmsSet()
        {
            this.AvailabilitySet = new HashSet<AvailabilitySet>();
        }
    
        public int Id { get; set; }
        public string NameFirm { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailabilitySet> AvailabilitySet { get; set; }
    }
}
